version: '3.8'

services:
  datadash:
    build: .
    container_name: datadash-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./frontend:/app/public
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: node src/server.js
    restart: unless-stopped
#     depends_on:
#       - mongodb

#   mongodb:
#     image: mongo:latest
#     container_name: datadash-mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#     restart: unless-stopped

# volumes:
#   mongodb_data:
